/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as StatusRouteImport } from './routes/status'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeSessionRouteImport } from './routes/practice.session'
import { Route as VocabularyIndexRouteImport } from './routes/vocabulary.index'
import { Route as VocabularyWordSlugRouteImport } from './routes/vocabulary.$wordSlug'
import { Route as LessonsLessonSlugIndexRouteImport } from './routes/lessons.$lessonSlug.index'
import { Route as LessonsLessonSlugTopicSlugRouteImport } from './routes/lessons.$lessonSlug.$topicSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSessionRoute = PracticeSessionRouteImport.update({
  id: '/practice/session',
  path: '/practice/session',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyIndexRoute = VocabularyIndexRouteImport.update({
  id: '/vocabulary/',
  path: '/vocabulary/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyWordSlugRoute = VocabularyWordSlugRouteImport.update({
  id: '/vocabulary/$wordSlug',
  path: '/vocabulary/$wordSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonSlugIndexRoute = LessonsLessonSlugIndexRouteImport.update({
  id: '/lessons/$lessonSlug/',
  path: '/lessons/$lessonSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonSlugTopicSlugRoute =
  LessonsLessonSlugTopicSlugRouteImport.update({
    id: '/lessons/$lessonSlug/$topicSlug',
    path: '/lessons/$lessonSlug/$topicSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grammar': typeof GrammarRoute
  '/reference': typeof ReferenceRoute
  '/status': typeof StatusRoute
  '/practice/session': typeof PracticeSessionRoute
  '/vocabulary/$wordSlug': typeof VocabularyWordSlugRoute
  '/practice/': typeof PracticeIndexRoute
  '/vocabulary/': typeof VocabularyIndexRoute
  '/lessons/$lessonSlug/$topicSlug': typeof LessonsLessonSlugTopicSlugRoute
  '/lessons/$lessonSlug/': typeof LessonsLessonSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grammar': typeof GrammarRoute
  '/reference': typeof ReferenceRoute
  '/status': typeof StatusRoute
  '/practice/session': typeof PracticeSessionRoute
  '/vocabulary/$wordSlug': typeof VocabularyWordSlugRoute
  '/practice': typeof PracticeIndexRoute
  '/vocabulary': typeof VocabularyIndexRoute
  '/lessons/$lessonSlug/$topicSlug': typeof LessonsLessonSlugTopicSlugRoute
  '/lessons/$lessonSlug': typeof LessonsLessonSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grammar': typeof GrammarRoute
  '/reference': typeof ReferenceRoute
  '/status': typeof StatusRoute
  '/practice/session': typeof PracticeSessionRoute
  '/vocabulary/$wordSlug': typeof VocabularyWordSlugRoute
  '/practice/': typeof PracticeIndexRoute
  '/vocabulary/': typeof VocabularyIndexRoute
  '/lessons/$lessonSlug/$topicSlug': typeof LessonsLessonSlugTopicSlugRoute
  '/lessons/$lessonSlug/': typeof LessonsLessonSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grammar'
    | '/reference'
    | '/status'
    | '/practice/session'
    | '/vocabulary/$wordSlug'
    | '/practice/'
    | '/vocabulary/'
    | '/lessons/$lessonSlug/$topicSlug'
    | '/lessons/$lessonSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grammar'
    | '/reference'
    | '/status'
    | '/practice/session'
    | '/vocabulary/$wordSlug'
    | '/practice'
    | '/vocabulary'
    | '/lessons/$lessonSlug/$topicSlug'
    | '/lessons/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/grammar'
    | '/reference'
    | '/status'
    | '/practice/session'
    | '/vocabulary/$wordSlug'
    | '/practice/'
    | '/vocabulary/'
    | '/lessons/$lessonSlug/$topicSlug'
    | '/lessons/$lessonSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GrammarRoute: typeof GrammarRoute
  ReferenceRoute: typeof ReferenceRoute
  StatusRoute: typeof StatusRoute
  PracticeSessionRoute: typeof PracticeSessionRoute
  VocabularyWordSlugRoute: typeof VocabularyWordSlugRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  VocabularyIndexRoute: typeof VocabularyIndexRoute
  LessonsLessonSlugTopicSlugRoute: typeof LessonsLessonSlugTopicSlugRoute
  LessonsLessonSlugIndexRoute: typeof LessonsLessonSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/session': {
      id: '/practice/session'
      path: '/practice/session'
      fullPath: '/practice/session'
      preLoaderRoute: typeof PracticeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/': {
      id: '/vocabulary/'
      path: '/vocabulary'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof VocabularyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/$wordSlug': {
      id: '/vocabulary/$wordSlug'
      path: '/vocabulary/$wordSlug'
      fullPath: '/vocabulary/$wordSlug'
      preLoaderRoute: typeof VocabularyWordSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonSlug/': {
      id: '/lessons/$lessonSlug/'
      path: '/lessons/$lessonSlug'
      fullPath: '/lessons/$lessonSlug/'
      preLoaderRoute: typeof LessonsLessonSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonSlug/$topicSlug': {
      id: '/lessons/$lessonSlug/$topicSlug'
      path: '/lessons/$lessonSlug/$topicSlug'
      fullPath: '/lessons/$lessonSlug/$topicSlug'
      preLoaderRoute: typeof LessonsLessonSlugTopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GrammarRoute: GrammarRoute,
  ReferenceRoute: ReferenceRoute,
  StatusRoute: StatusRoute,
  PracticeSessionRoute: PracticeSessionRoute,
  VocabularyWordSlugRoute: VocabularyWordSlugRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  VocabularyIndexRoute: VocabularyIndexRoute,
  LessonsLessonSlugTopicSlugRoute: LessonsLessonSlugTopicSlugRoute,
  LessonsLessonSlugIndexRoute: LessonsLessonSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
